version: '2.0'

services:
  config-server: 
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always
    networks: 
      - springcloud

  eureka-server: 
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks: 
      - springcloud

  servicio-mysql: 
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks: 
      - springcloud
    environment: 
      MYSQL_DATABASE: db_spring_cloud
      MYSQL_ROOT_PASSWORD: 249861

  servicio-productos: 
    image: servicio-productos:v1
    restart: always
    networks: 
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - servicio-mysql
      
  servicio-item: 
    image: servicio-item:v1
    ports:
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    restart: always
    networks: 
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - servicio-productos
      
  zuul-server: 
    image: zuul-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks: 
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - servicio-productos
      - servicio-item

networks: 
  springcloud:

